### ISSUE TITLE
"Could not run stream through document bundle processor"

### ISSUE THREAD

**Issue by Trondelond** [digipost/signature-api-client-dotnet#102]
Hei,

Under PortalClient.Create(Job) får jeg følgende feilmelding i respons : 
```
The server encountered an error processing the request. The exception message is 'Could not run stream through document bundle processor.'. See server logs for more details. The exception stack trace is: 
at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceArchive.SendArchiveThroughBundleProcessors(Byte[] archiveBytes) 
at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceArchive.GetBytes() 
at Digipost.Signature.Api.Client.Portal.Internal.AsicE.PortalAsiceGenerator.CreateAsice(Job job, X509Certificate2 certificate, IAsiceConfiguration asiceConfiguration)
at Digipost.Signature.Api.Client.Portal.PortalClient.&lt;Create&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

Koden er oppe og går fint i utviklingsmiljø, samme kall fungerer prikkfritt der. Når dette flyttes til testmiljø får jeg denne meldingen når Create() kalles. Kan dette være sertifikat-relatert?

**Comment by Trondelond** [comment]
Hvis noen skulle gå seg på den samme feilmeldingen, viste det seg at løsningen (naturlig nok) var at clientconfiguration var satt til å logge : 
```

clientConfiguration = new ClientConfiguration(...);
clientConfiguration.LogRequestAndResponse = true;
clientConfiguration.EnableDocumentBundleDiskDump(logFilePath);

```

..og pathen som `logFilePath` pekte til eksisterte ikke.
