### ISSUE TITLE
.NET Core compatible version

### ISSUE THREAD

**Issue by Manojb86** [digipost/signature-api-client-dotnet#127]
Hi,
Aren't there .NET Core compatible version of this library? if I want to use this library with .NET Core based application, how do I do that?

**Comment by asjafjell** [comment]
Hi, @Manojb86!

We have tried to convert the library to netstandard2 over the last few weeks. We were almost successful, but a few extra hurdles needs to be overcome before we can release it. The problems are related to _Two way TLS_, certificate handling and logging. We can release a .NET Core compatible version as soon as these problems are resolved. 

Unfortunately, I am unable to give you a date for when this will be resolved, as these are mostly external dependencies.

**Comment by asjafjell** [comment]
Hi again! As soon as .NET Core 2.1 was released, the fix for two way TLS was fixed. We are now ready with a .NET Core version. 🎉 For mor information, see [5.0.2 Release notes](https://github.com/digipost/signature-api-client-dotnet/releases/tag/v5.0.2)

**Comment by Ovini** [comment]
Hi asjafjell,

Are there more steps to follow when use with Docker?

I use Digipost.Signature.Api.Client.Direct 5.02 with .net core 2.1 solution. It works fine with IIS. When we run it as a Linux docker container on Linux server I get below error message while creating a signature job.
           `var job = new Job(documentToSign, signers, "SendersReferenceToSignatureJob", exitUrls);
            var directJobResponse = await directClient.Create(job);`

Here is the error log.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Digipost.Signature.Api.Client.Core.Internal.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Digipost.Signature.Api.Client.Core.Internal.UserAgentHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Digipost.Signature.Api.Client.Core.Internal.RequestHelper.Create[T](Uri uri, HttpContent content, Func`2 deserializeFunc)
   at Digipost.Signature.Api.Client.Direct.DirectClient.Create(Job job)
   at FormsEngine.DigiPost.Services.DigiPostSignatureService.CreateSignatureJob(String sessionId, String documentTitle, String fNr, String senderOrgNr, Byte[] documentBytes) in /src/src/FormsEngine.DigiPost/Services/DigiPostSignatureService.cs:line 201

Please Help.

**Comment by asjafjell** [comment]
Hi. It is hard for me to assist you on Docker issues, as there can be a lot of different things. But as you can see of the error message you get _certificate unknown_. Have you remembered to give the Docker container access to the certificate path? This is unfortunately all the information I can give you. If you got the client library to work with the old rig, and it is not working in Docker, you will have to check your Docker configuration. The library itself has no direct relation to Docker.

**Comment by sveinblad** [comment]
Please set the <TargetFramework> to netstandard2.0 in your next release. No reason to target netcoreapp2.1 in particular.

**Comment by sveinblad** [comment]
Hi ovini,

have a look at the documentation found here:

https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md

**Comment by Ovini** [comment]
Thanks for all solutions. I tried many options but still same error.  With those experience now I believe there might be an issue with SSl stuff on Linux server. Trying to figure out it something....

**Comment by asjafjell** [comment]
I can confirm that we seem to have the same problem on our build server which is running Linux. Please let us know what is causing the issue for you and a possible solution if you find it.

**Comment by Ovini** [comment]
As I guess the issue was with our Dabian Linux server. Admin team has resolved it and finally digipost works for us. Here is the answer I got from Admin team
......................................................................................................................................
To make this work with DigiPost test environment, you have to add CA root+intermediate certificates for Buypass and Commfides. These can be downloaded here:

https://begrep.difi.no/SikkerDigitalPost/1.2.6/sikkerhet/sertifikathandtering

I believe we only need the certificates for Buypass to get DigiPost to work, but it won't hurt to install both.
The Buypass certificates are in DER format, so they need to be converted to PEM before they can be installed on a Debian server:

# openssl x509 -inform der -in certificate.cer -out certificate.pem

Place the PEM certificates in /usr/local/share/ca-certificates, then run "update-ca-certificates" to have them included in /etc/ssl/certs

For production, there is a diffenrent set of certificates to install. They can be downloaded from the same page.

**Comment by asjafjell** [comment]
Great work, @Ovini! I have done some debugging myself, and that last bit was really useful information for me, as I have limited Linux experience. Installing the PEM-certificates into the ca-certificates did the trick! This will be a part of our guide for setup.

**Comment by asjafjell** [comment]
We have now added your findings in the [new documentation for the client library](https://signering-docs.readthedocs.io/en/latest/install-enterprise-certificate.html). Closing this for now. Thanks again for your help.
