### ISSUE TITLE
Exception: Key not valid for use in specified state. 

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#71]
Hei, se exception nedenfor. Ser ut som om noe er galt med virksomhetssertifkatet? Det samme sertifikatet fungerer fra min utviklermaskin, men feiler i vårt verifikasjonsmiljø. Jeg går mot miljø "DifiTest". Bruker versjon 1.4.6026.24181 av klienten. Når jeg har importert virksomhetssertifikatet har jeg huket av for "Mark this key as exportable."

````
Inner exception: Type: Digipost.Signature.Api.Client.Core.Exceptions.XmlParseException
Melding: Kunne ikke bygge Xml for signatur.
Stakkspor:
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.Xml()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.get_Bytes()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceArchive.<>c.<.ctor>b__3_0(IAsiceAttachable a)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceArchive..ctor(IEnumerable`1 asiceAttachableProcessors, IAsiceAttachable[] attachables)
   at Digipost.Signature.Api.Client.Direct.Internal.AsicE.DirectAsiceGenerator.CreateAsice(Job job, X509Certificate2 certificate, IAsiceConfiguration asiceConfiguration)
   at Digipost.Signature.Api.Client.Direct.DirectClient.d__2.MoveNext()
````

````
Inner exception: Type: System.Exception
Melding: Angitt sertifikat med fingeravtrykk E395C514D86EB0880D2D78BEF1D13323384E1A50 kan ikke eksporteres. Det er nødvendig når sertifikatet ikke er opprettet med 'Microsoft Enhanced RSA and AES Cryptographic Provider' som CryptoAPI provider name (-sp parameter i makecert.exe eller -csp parameter i openssl).
Stakkspor:
   at Difi.Felles.Utility.Security.SignedXmlWithAgnosticId..ctor(XmlDocument xmlDocument, X509Certificate2 certificate, String inclusiveNamespacesPrefixList)
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.CreateSignatureElement()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.CreateXadesSignature()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.Xml()
````

````
Inner exception: Type: System.Security.Cryptography.CryptographicException
Melding: Key not valid for use in specified state. 
Stakkspor:
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey, Int32 blobType, Object cspObject)
   at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSA.ToXmlString(Boolean includePrivateParameters)
   at Difi.Felles.Utility.Security.SignedXmlWithAgnosticId..ctor(XmlDocument xmlDocument, X509Certificate2 certificate, String inclusiveNamespacesPrefixList)
````

**Comment by asjafjell** [comment]
Jeg mistenker sterkt at du ikke har huket av for "Mark this key as exportable". Det er det eneste som jeg har opplevd at dette skjer på. Er du sikker på at du bruker det samme sertifikatet som du har importert? Du kan sjekke Microsoft Management Console og verifisere at det går an å eksportere det derfra.

**Comment by sukchr** [comment]
Hei, du har rett!

**Comment by asjafjell** [comment]
Flott at det løste seg! Det er fint for oss om du kunne undersøke ulike feilkilder selv før du oppretter issues i fremtiden. På denne måten sparer du oss for tid, og du slipper å vente på at vi har tid til å feilsøke og svare deg :slightly_smiling_face:

**Comment by sukchr** [comment]
Takk, det skal jeg gjøre.

**Comment by ravibansal1208** [comment]
Hi, I also got an error "Kunne ikke bygge Xml for signature" and when I made a certificate exportable then it still complains about the same. are there other things which can be checked?

**Comment by runeflobakk** [comment]
@ravibansal1208 Please open a new issue, and provide the full error you receive.

**Comment by ravibansal1208** [comment]
@runeflobakk Opened a new one on 
https://github.com/digipost/signature-api-client-dotnet/issues/430
