### ISSUE TITLE
Oppgradering av Difi-felles-utility-dotnet feiler

### ISSUE THREAD

**Issue by bjornk** [digipost/signature-api-client-dotnet#73]
Hei.
Vi bruker signeringsklient og kontaktregisterklient i samme .net-løsning.
Etter oppgradering av pakken Difi.Oppslagstjeneste.Klient til siste versjon, feiler forsøk på å oppgradere Difi-felles-utility-dotnet:

_"Updating 'difi-felles-utility-dotnet 0.6.6008.19059' to 'difi-felles-utility-dotnet 0.7.6071.14316' failed. Unable to find a version of 'difi-oppslagstjeneste-klient' that is compatible with 'difi-felles-utility-dotnet 0.7.6071.14316'."_

Kan enkelt gjenskapes i Visual Studio ved å først installere pakken Difi.Oppslagstjeneste.Klient, og deretter difi-felles-utility-dotnet.

Når vi prøver å kjøre signering uten å oppgradere difi-felles-utility-dotnet, får vi feilmelding:

_System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.String Difi.Felles.Utility.XmlValidator.get_ValidationWarnings()'.
   at Digipost.Signature.Api.Client.Core.Internal.XsdValidationHandler.ValidateXmlAndThrowIfInvalid(String xml)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.<ValidateAndThrowIfInvalid>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.RequestHelper.<Create>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Direct.DirectClient.<Create>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Kommune247.Controllers.ViewerController.Sign() in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 881
   at Kommune247.Controllers.ViewerController.DoAction(String action) in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 311
   at Kommune247.Controllers.ViewerController.New(String shortname, Nullable`1 version, String action) in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 81_

Mvh.
Bjørn K.
Sem & Stenersen Prokom

**Comment by asjafjell** [comment]
Hei!

Dette er veldig uheldig, og kommer av at Visual Studio ikke respekterer pakkerestriksjonene og lar deg oppgradere til nyeste versjon, selv om det ikke vil kompilere. Dette har vi opplevd i Visual Studio 2015 Update 1, og er fikset i Update 3. Hvilken versjon bruker du?

**Comment by sukchr** [comment]
PS: vi får en runtime-error (ikke compiletime-error).

Hvis dere ønsker å sette en øvre begrensning på versjonsnummeret på en avhengighet, må det settes version range i .nuspec-fila. Se https://docs.nuget.org/create/versioning. 

Så vidt jeg kan se er det ikke oppgitt øvre grense for difi-felles-utility i nuspec for signeringsklienten - https://github.com/digipost/signature-api-client-dotnet/blob/master/signature-api-client.nuspec.

**Comment by asjafjell** [comment]
Beklager, jeg ordla meg feil her. Den prøver å linke inn avhengigheten under kjøring og det feiler. Her er det altså begrensningene satt i Posten Signering som gjelder. Disse har kun en nedre begrensning, så her har du helt rett @sukchr! Dette skal vi få fikset snarlig.

**Comment by sukchr** [comment]
Supert, takk :)

**Comment by asjafjell** [comment]
Fram til da er det bare å installere siste 0.6-versjon av difi-felles-utility, så skal det ordne seg.

**Comment by bjornk** [comment]
Ja, men det er da vi får feilmeldingen ved runtime, altså den siste feilmelding som jeg meldte inn:

System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.String Difi.Felles.Utility.XmlValidator.get_ValidationWarnings()'.
at Digipost.Signature.Api.Client.Core.Internal.XsdValidationHandler.ValidateXmlAndThrowIfInvalid(String xml)
at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Digipost.Signature.Api.Client.Core.Internal.RequestHelper.d__41.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Digipost.Signature.Api.Client.Direct.DirectClient.<Create>d__2.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
at Kommune247.Controllers.ViewerController.Sign() in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 881
at Kommune247.Controllers.ViewerController.DoAction(String action) in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 311
at Kommune247.Controllers.ViewerController.New(String shortname, Nullable`1 version, String action) in c:\Repo\Products\kommune24-7\src\Kommune24-7\Controllers\ViewerController.cs:line 81

**Comment by sukchr** [comment]
Bare for å være helt tydelig, så gir denne comboen:

````
  <package id="difi-felles-utility-dotnet" version="0.6.6008.19059" targetFramework="net45" />
  <package id="difi-oppslagstjeneste-klient" version="5.3.6024.16371" targetFramework="net45" />
  <package id="digipost-signature-api-client" version="1.5.6073.22973" targetFramework="net45" />
````

denne feilen:
````
Inner exception: Type: System.MissingMethodException
Message: Method not found: 'System.String Difi.Felles.Utility.XmlValidator.get_ValidationWarnings()'.
Stacktrace:
   at Digipost.Signature.Api.Client.Core.Internal.XsdValidationHandler.ValidateXmlAndThrowIfInvalid(String xml)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.RequestHelper.d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Direct.DirectClient.d__2.MoveNext()
````

**Comment by sukchr** [comment]
Hei, kan dere si noe om når dere regner med å ha en løsning? Vi er ikke avhengige av å benytte aller siste versjon av pakkene, så hvis det kan være en løsning å "nedgradere" noen av pakkene er vi åpne for det.

**Comment by asjafjell** [comment]
Det ble glemt av å poste etter at vi fikset dette. Vi lastet opp en ny [beta-versjon](https://www.nuget.org/packages/digipost-signature-api-client/1.6.6089.28313-beta) av klienten på fredag som skal ha siste versjon av avhengigheten `difi-felles-utility`. Beklager at dette ikke ble annonsert.

**Comment by sukchr** [comment]
Takk, da tester vi den!

**Comment by sukchr** [comment]
Takk for hjelpen! Bekrefter at denne kombinasjonen fungerer:

````
  <package id="difi-felles-utility-dotnet" version="0.6.6008.19059" targetFramework="net45" />
  <package id="difi-oppslagstjeneste-klient" version="5.3.6024.16371" targetFramework="net45" />
  <package id="digipost-signature-api-client" version="1.6.6089.28313-beta" targetFramework="net45" />
````
