### ISSUE TITLE
.NET klienten og fiddler

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#96]
Når fiddler kjører får vi følgende feilmelding:

```
{
  "message": "An error has occurred.",
  "exceptionMessage": "An error occurred while sending the request.",
  "exceptionType": "System.Net.Http.HttpRequestException",
  "stackTrace": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Digipost.Signature.Api.Client.Core.Internal.LoggingHandler.<SendAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Digipost.Signature.Api.Client.Core.Internal.UserAgentHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Acos.Felles.Signering.Providers.Difi.Services.DifiSignService.<CheckStatus>d__8.MoveNext() in C:\\code\\Acos.Felles.Signering\\Acos.Felles.Signering\\Providers\\Difi\\Services\\DifiSignService.cs:line 362\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Acos.Felles.Signering.Controllers.SignStatusController.<GetSignatureJobs>d__3.MoveNext() in C:\\code\\Acos.Felles.Signering\\Acos.Felles.Signering\\Controllers\\SignStatusController.cs:line 40\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
  "innerException": {
    "message": "An error has occurred.",
    "exceptionMessage": "The underlying connection was closed: An unexpected error occurred on a send.",
    "exceptionType": "System.Net.WebException",
    "stackTrace": "   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)",
    "innerException": {
      "message": "An error has occurred.",
      "exceptionMessage": "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.",
      "exceptionType": "System.IO.IOException",
      "stackTrace": "   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)\r\n   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)\r\n   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)",
      "innerException": {
        "message": "An error has occurred.",
        "exceptionMessage": "An existing connection was forcibly closed by the remote host",
        "exceptionType": "System.Net.Sockets.SocketException",
        "stackTrace": "   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)"
      }
    }
  }
}


```
Vi ser også at vi får : Could not create SSL/TLS secure channel.
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.LoggingHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.UserAgentHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Core.Internal.XsdRequestValidationHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

1. Da er dette kanskje to spørsmål, kan vi kjøre Fiddler når vi bruker .NET klienten og evt hvordan?
2. Could not create SSL/TLS secure channel et rent sertifikat problem, eller kan dette også skje hvis trafikken går gjennom en proxy?

**Comment by talisker77** [comment]
Klientbiblioteket fungerer fint uten proxy og fungerer fint uten fiddler.
Men når exception skjer i .net klienten, så er det naturlig å henvende seg til dere, kanskje dere til og med hadde et svar...

**Comment by asjafjell** [comment]
Beklager at dette ikke er svaret du ønsker, men om klienten leverer uten bruk av Fiddler og proxy så er dette utenfor vår kontroll. At du plasserer programvare i nettverkslaget mellom klienten og serveren er høyst uvanlig og klienten har ikke mulighet til å se eller håndtere et slikt scenario.

**Comment by anvike** [comment]
Hei,

Erlend er på ferie, så jeg prøver meg på å ta saken litt videre. Vi har nå fått bekreftet at vi får samme feilmelding selv uten bruk av proxy og fiddler. 
Vi har også verifisert at serveren kan snakke med https://api.signering.posten.no/api/[org-nummer], og at opplysninger rundt sertifikatet er riktig. Vi står da litt fast her, og lurer på om det da er noe mer vi bør være oppmerksom på for å kunne oppnå tilkobling til api'en.

-André

**Comment by asjafjell** [comment]
1. Har dere gått mot det endepunktet med noe annet enn dotnet-klienten? Jeg er litt nysgjerrig på hvorfor @talisker77 sier at det fungerer fint, mens du, @anvike sier at det ikke gjør det.
2. Hvis dere bruker dotnet-klienten når denne feilen oppstår, kunne jeg fått eksempelkode som viser hva dere gjør, og akkurat hva som feiler?

**Comment by anvike** [comment]
Hei igjen,

Kommunikasjon med api er nå opprettet, og ser tilsynelatende ut til å fungere som forventet. Problemet viste seg å ligge i feil sertifikattype som var installert på server. 
Grunnen til de to sprikende tilbakemeldingene fra oss skyldes at vi refererte til to forskjellige installasjoner som vi så på som tilnærmet identisk satt opp, beklager forvirringen her. 

-André

**Comment by asjafjell** [comment]
Supert at dere fikk det til å fungere! Jeg lukker denne. Ikke nøl med å legge inn et nytt issue om dere skulle støte på flere problemer.
